apiVersion : apps/v1
kind: Deployment
metadata:
  name: delivery
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: delivery
    spec:
      containers:
        - name: delivery
          image: myeventstormingregistry.azurecr.io/delivery
          ports:
            - containerPort: 8080
